#!/bin/bash
find . -type f -iname '*.gif' -exec sh -c 'for f do echo $(stat -c "%s %n" "$f" | sed "s/\.gif$//"); done | sort -f -n | awk "{sub(/^\.\\//,\"\"); sub(/\.gif$/,\"\",\$NF); print \$NF}"' sh {} +
